#!/bin/sh

# macOS:
#
# $ sudo port install coreutils
# $ file -h `which kindlepreviewer `
# /Users/alex/bin/kindlepreviewer: symbolic link to /Applications/Kindle Previewer 3.app/Contents/MacOS/Kindle Previewer 3

type kindlepreviewer || exit 1

file -b --mime-type "$1" | grep -qx application/epub+zip || {
    echo payload is not epub 1>&2
    exit 1
}

mv "$1" "$1.epub"

# at the time of writing, Kindle Previewer always return exit code 0,
# even if its conversion failed
kindlepreviewer "$1.epub" -convert

kpf=`find . -type f | grep -m1 kpf` || {
    echo conversion failed
    exit 1
}
mv "$kpf" result
