#!/usr/bin/env -S gstdbuf -o0 -e0 bash

# macOS:
#
# $ sudo port install coreutils
# $ file -h `which kindlepreviewer `
# /Users/alex/bin/kindlepreviewer: symbolic link to /Applications/Kindle Previewer 3.app/Contents/MacOS/Kindle Previewer 3

type kindlepreviewer || exit 1

mv "$1" "$1.epub"
kindlepreviewer "$1.epub" -convert

kpf=`find . -type f | grep -m1 kpf` || {
    echo conversion failed
    exit 1
}
mv "$kpf" result
