#!/usr/bin/env -S stdbuf -o0 -e0 bash

type kindlepreviewer || exit 1

mv "$1" "$1.epub"
kindlepreviewer "$1.epub" -convert

kpf=`find . -type f | grep -m1 kpf` || {
    echo conversion failed
    exit 1
}
mv "$kpf" result
