#!/bin/sh

errx() { echo "$*"; exit 1; }

kindlepreviewer='/Applications/Kindle Previewer 3.app/Contents/MacOS/Kindle Previewer 3'

file -b --mime-type "$kindlepreviewer" |
    grep -m1 -qx application/x-mach-binary ||
    errx "not an executable: $kindlepreviewer"

file -b --mime-type "$1" | grep -qx application/epub+zip ||
    errx payload is not epub

mv "$1" "$1.epub"

# at the time of writing, Kindle Previewer always return exit code 0,
# even if its conversion failed
"$kindlepreviewer" "$1.epub" -convert

kpf=`find . -type f | grep -m1 kpf` || errx conversion failed
mv "$kpf" result
