#!/usr/bin/env -S stdbuf -o0 -e0 bash

[ "$1" = "-h" ] && {
    echo 'Remote uptime(1)' > result
    exit
}

[ "$1" = "-1" ] && {
    echo 'testing exit code 1' 1>&2
    exit 1
}

echo Wait...
sleep 5
uptime > result
